### ISSUE TITLE
RcppDeepState fuzz testing

### ISSUE THREAD

**Issue by tdhock** [tdhock/LOPART#1]
hey @akhikolla here is a new R package I wrote this week, can you please try to fuzz test this using RcppDeepState?

**Comment by akhikolla** [comment]
Sure @tdhock. I'll test the package.

**Comment by akhikolla** [comment]
Hello @tdhock ,
I fuzz tested the package using DeepState and Valgrind.  It looks like all the tests passed if the exceptions thrown by the rcpp functions are handled. 
DeepState gave a message like INFO: Done fuzzing! Ran 7 tests (0 tests/second) with 0 failed/7 passed/0 abandoned tests. Below is the log file executing the testharness along with the inputs passed on to the function.
[LOPARTexpectionshandled.txt](https://github.com/tdhock/LOPART/files/4733407/LOPARTexpectionshandled.txt)

Without handling the exceptions the log file gives the errors and stack trace of the errors:
[LOPARTunhandledexceptions.txt](https://github.com/tdhock/LOPART/files/4733410/LOPARTunhandledexceptions.txt)

**Comment by tdhock** [comment]
ok thanks.
you may add this to your list of Rcpp packages you can use to test RcppDeepState
